[tool.poetry]
name = "site de reservas"
version = "0.1.0"
description = ""
authors = ["Levy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^23.9.1"
django = "^4.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
