# Generated by Django 4.2.5 on 2023-10-05 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quartos",
            old_name="fktipo_Quarto",
            new_name="fk_tipoQuarto",
        ),
    ]
