# Generated by Django 4.2.5 on 2023-09-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupacao',
            name='fk_cliente',
        ),
        migrations.RemoveField(
            model_name='ocupacao',
            name='fk_quarto',
        ),
        migrations.RemoveField(
            model_name='ocupacao',
            name='fk_tipooccup',
        ),
        migrations.RemoveField(
            model_name='quartos',
            name='fktipo_Quarto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Ocupacao',
        ),
        migrations.DeleteModel(
            name='Ocupacao_tipo',
        ),
        migrations.DeleteModel(
            name='Quarto_Cat',
        ),
        migrations.DeleteModel(
            name='Quartos',
        ),
    ]
